.Dd June 25, 2019 
.Dt VF1 1
.Os All Operating Systems
.Sh NAME
.Nm vf1
.Nd command line gopher client
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl \-bookmarks
.Op Fl \-debug
.Op Fl \-tls
.Op Ar url ...
.Sh DESCRIPTION
.Nm
is an interactive command line gopher client.
It presents a prompt to the user, which can then enter commands to perform
actions.
.Pp
You only need a small number of commands to get around, and most of
them can be abbreviated to one or two chars, so with practice you can get
around very quickly.
See the
.Sx COMMANDS
section for more details.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h , \-help
Display a short help message and exit.
.It Fl \-bookmarks
Open your bookmarks.
.It Fl \-debug
Open with debug mode enabled.
.It Fl \-tls
Open in TLS mode.
That is, all the links you're following are expected to go to TLS enabled
servers.
This is the equivalent of using the
.Ic tls
command to switch to TLS mode.
.It Ar url ...
The Gopher URLs to open.
If you just supply a hostname, the standard port is going to be used.
The standard port is 70.
If you provide more than one URL, these are queued in a
.Ic tour .
.El
.Ss Concepts
Those are some key concepts to understand how
.Nm
works.
.Bl -bullet
.It
.Nm
always has in it's mind exactly one
.Dq index ,
i.e. a list of places in Gopherspace with numbers attached to them. By
typing
.Ic 1
and enter,
.Ic 2
and enter, etc. you jump to that location in the active index.
.It
Whenever you visit a gopher menu, the contents of that menu become the
active index, replacing whatever it used to be.
.It
When you do
.Ic search
or
.Ic history
or
.Ic links ,
the results of these commands overwrite your current index.
If you want to get your index back to being the most recently visited gopher
menu, you can use the
.Ic ls
command.
Doing this means you lose your search results (your history doesn't go away,
though).
.It
The
.Ic search
command runs on whatever the current index is.
This might not be the contents of a gopher menu.
You can search your history, and in fact you can even search the results of an
earlier search to narrow things down!
.It
In general,
.Nm
does not remember much.
It always has some idea of the most recently visited gopher menu (i.e. itemtype
1) and the most recently visited gopher document (i.e. any other itemtype).
The
.Ic ls
command always operates on the most recently visited gopher
.Em menu ,
even if you have visited some documents since then.
Commands like
.Ic fold ,
.Ic less
and
.Ic save
operate on the most recently visited
.Em document ,
even if you have visited some menus since then.
Basically everything operates one the most recently seen thing of the
appropriate type.
.El
.Pp
.Ss Handlers
.Pp
.Nm
uses external programs as
.Dq handlers
to present gopherspace content to you.
Even when you visit a plain text file with item type 0,
.Nm
spawns (by
default) the unix command
.Xr cat 1
to display that file on your screen, rather than using a Python
.Fn print
call.
You have full control over which external programs are used for different
content, so you can customise your user experience.
.Pp
Handlers are assigned on the basis of MIME types.
The gopher protocol has no concept of MIME, so
.Nm
assigns each item a MIME
type as follows:
.Bl -bullet
.It
Item types 0 and 1 are assigned MIME type
.Ql text/plain
.It
Item type h is assigned MIME type
.Ql text/html
.It
Item type g is assigned MIME type
.Ql image/gif
.El
.Pp
For all other item types,
.Nm
attempts to guess a MIME type from the file
extension of the last component of the selector, using the
.Ql mimetypes
module from the Python standard library.
This usually results in a reliable identification assuming the file has an
extension and the author of the gopher content is not actively trying to
deceive you.
.Pp
If the selector has no file extension, or the extension is not
recognised by the
.Ql itemtypes
module,
.Nm
will use the unix program
.Xr file 1
to attempt to guess a MIME type by actually inspecting the content of
the file.
.Pp
In accordance with the idea that gopher item types, which are a
standard part of the protocol, should take precedence over any other
attempt at inferring MIME type, which is not a standard part of the
protocol, if an item in gopherspace is listed with itemtype
.Ql I
or
.Ql s
and one of the above methods returns a MIME type which does not begin
with
.Ql image/
or
.Ql sound/
respectively,
.Nm
will default to
.Ql image/jpeg
or
.Ql audio/mpeg
respectively.
This should only happen in highly unusual circumstances and suggests a poorly
or maliciously configured gopher server.
.Pp
Once a MIME type has been identified for an item, an appropriate handler
program will be used to handle the content.
You can view a list of the current handler assignments at any time by running
the
.Ic handler
command.
The default handlers that ship with
.Nm
are:
.Bl -column -offset indent "application/pdf" "lynx -dump -force_html %s"
.It Sy handler          Ta Sy program
.It application/pdf:    Ta xpdf %s
.It audio/mpeg:         Ta mpg123 %s
.It audio/ogg:          Ta ogg123 %s
.It image/*:            Ta feh %s
.It text/html:          Ta lynx -dump -force_html %s
.It text/plain:         Ta cat %s
.El
.Pp
You can also use the
.Ic handler
command to change these handlers, or set handlers for new MIME types.
For example, if you prefer using
.Xr w3m 1
over
.Xr lynx 1
for handling HTML content, you could run:
.Pp
.Dl VF-1> handler text/html w3m -dump %s
.Pp
You can use the
.Ql *
wildcard when specifying handler MIME types, such as
.Ql image/*
to use a single program to handle any kind of image.
Handlers without wildcards take precedence over handlers with wildcards.
In other words, if you specify, e.g. one handler for
.Ql image/jpeg
and a different handler for
.Ql image/* ,
the
.Ql image/jpeg
handler will be used for JPEGs and the
.Ql image/*
handler will be used for all other images.
.Pp
.Ss Text encoding
.Pp
.Nm
attempts to decode the content received for any text-based item
types (e.g. 0, 1, 7, h) as UTF-8.
Most content in gopherspace is ASCII-encoded, and since UTF-8 is backward
compatible with ASCII, this will generally
.Dq just work .
If the received content
.Em cannot
be decoded as UTF-8, one of two possible things will happen:
.Pp
If the
.Ql chardet
Python module is installed on your system,
.Nm
will use it to attempt to
automatically detect the encoding used and decode the text appropriately.
Note that pip etc. will not install
.Ql chardet
for you when you install
.Nm ,
as
.Nm
does not formally depend on
.Ql chardet .
It uses it opportunistically, so that it can still be easily installed
and used on systems where
.Ql chardet
is not or cannot be installed.
.Pp
If
.Ql chardet
is not installed, or if
.Ql chardet
cannot identify an encoding with confidence exceeding 0.5,
.Nm
will attempt to
fall back to a single, user-specified alternative encoding.
This encoding can be set as follows:
.Pp
.Dl VF-1> set encoding koi8-r
.Pp
The default fall back encoding is iso-8559-1, which is used by the
popular gopher site
.Lk floodgap.com .
If you routinely visit gopher sites encoded with some other encoding, consider
using an RC file (see below) to automatically set your alternative encoding at
start up.
.Sh COMMANDS
.Bl -tag -width Ds
.It Ic a , add
Add the current URL to the bookmarks menu.
.It Ic b , back
Go back to the last gopher menu.
.It Ic bb , blackbox
Display contents of flight recorder, showing statistics for the current gopher
browsing session.
.It Ic bm , book , bookmarks
Show the current bookmarks menu.
.It Ic f , fold
Process the text of the most recently visited item with the
.Xr fold 1
command.
.It Ic fo , forward
Go forward to the next gopher item.
.It Ic g , go Ar url | mark
Go to a gopher URL or marked item.
.It Ic handler Op Ar mimetype Ar program
List or set handlers for different MIME types.
.It Ic h , hist , history
Display history.
.It Ic l , less
Process the text of the most recently visited item with the
.Xr less 1
command.
.It Ic li , links
Extract URLs from most recently visited item.
.It Ic m , mark Ar mark
Mark the current item with a single letter.
This letter can then be passed to the
.Ic go
command to return to the current item later.
Think of it like marks in vi.
.It Ic n , next
Go to next item after current in index.
.It Ic p , prev, previous
Go to previous item before current in index.
.It Ic q , quit
Exit VF-1.
.It Ic r , reload
Reload the current URL.
.It Ic s , save Op Ar filename
Save an item to the filesystem.
.Ic save Cm n Cm filename
saves menu item n to the specified filename.
.Ic save Cm filename
saves the last viewed item to the specified filename.
.Ic save Cm n
saves menu item n to an automagic filename.
.It Ic / , se , search Ar pattern
Search index (case insensitive).
.It Ic t , tour Op Ar item ...
Add index items as way points on a tour, which is basically a FIFO
queue of gopher items.
Items can be added with
.Ic tour Cm "1 2 3 4"
or ranges like
.Ic tour Cm 1-4 .
All items in current menu can be added with
.Ic tour Cm * .
Current tour can be listed with
.Ic tour Cm ls
and scrubbed with
.Ic tour Cm clear .
.It Ic up , Ic u
Go up one directory in the path.
.It Ic v , veronica
Submit a search query to the Veronica 2 search engine.
.El
.Sh FILES
.\" the longest path name appearing in the list
.Bl -tag -width ~/.vf1-bookmarks.txt -compact
.It Pa ~/.vf1-bookmarks.txt
This file stores your bookmarks. Use
.Ic add
to add the current URL to your bookmarks. Feel free to edit the file
and rearrange the bookmarks using a text editor. This files is a
simple gopher map.
.It Pa ~/.config/vf1/vf1rc
.It Pa ~/.config/.vf1rc
.It Pa ~/.vf1rc
Upon startup,
.Nm
will search for a file with one of these names, a so-called RC file
(see below). The names are listed above in order of preference and
.Nm
will stop after the first one it finds, e.g. if you have both a
.Pa ~/.config/vf1/vf1rc
and a
.Pa ~/.vf1rc
then
.Pa ~/.vf1rc
will be ignored.
.El
.Ss RC FILE
If such a file is found, each line of the file will be executed as a
.Nm
command before the prompt is displayed. This allows you to script
certain commands that you want to be run every time you start
.Nm .
This lets you:
.Bl -bullet
.It
Permanently configure item type handlers by putting
.Ic handler
commands in the RC file.
.It
Permanently configure any options, such as whether or not to use
coloured output or your preferred non-UTF-8 encoding, by putting
.Ic set
commands in the RC file.
.It
Set a
.Dq home page
by putting a
.Ic go
command in the RC file.
.It
Start a tour through your favourite sites by putting
.Ic tour
commands in the RC file.
.El
.Sh EXAMPLES
See the
.Xr vf1-turorial 7
for a comprehensive introduction to the work flow of
.Nm
.Pp
Start
.Nm :
.Pp
.Dl vf1
.Pp
Start
.Nm
with your bookmarks:
.Pp
.Dl vf1 --bookmarks
.Pp
Visit the zaibatsu:
.Pp
.Dl vf1 zaibatsu.circumlunar.space
.Sh SEE ALSO
.Xr vf1-tutorial 7
.Bl -bullet
.It
.Lk https://docs.python.org/3.5/library/mimetypes.html mimetypes
.It
.Lk https://pypi.python.org/pypi/chardet chardet
.El
.Sh STANDARDS
.Nm
is a gopher client conforming to RFC 1436
.Aq Lk https://tools.ietf.org/html/rfc1436 .
.Sh AUTHORS
.An Solderpunk
.Aq Mt solderpunk@sdf.org
.An Alex Schroeder
.Aq Mt alex@gnu.org
.An Joseph Lyman
.Aq Mt tfurrows@sdf.org
.An Adam Mayer
.Aq Lk https://github.com/phooky
.An Paco Esteban
.Aq Mt paco@onna.be
